timestamp,result,status,message
2024/07/18 11:58:05,0,error,"2024/07/18 11:58:05: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd4146a1610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2024/07/18 12:02:54,0,error,"2024/07/18 12:02:54: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6778081790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2024/07/18 15:25:33,0,error,"2024/07/18 15:25:33: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb9be70760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2024/07/18 15:26:55,0,error,"2024/07/18 15:26:55: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1097072790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2024/07/18 15:27:55,0,error,"2024/07/18 15:27:55: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1097072580>: Failed to establish a new connection: [Errno 111] Connection refused'))"
2024/07/18 15:40:42,0,error,"2024/07/18 15:40:42: Error making POST request: HTTPSConnectionPool(host='192.168.3.117', port=10443): Max retries exceeded with url: /?rest_route=/trafficinfo/v1/update (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47d58816a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
